/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAddRouteImport } from './routes/_app/add'
import { Route as AppClosetRouteImport } from './routes/_app/closet'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppLooksRouteImport } from './routes/_app/looks'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppRoomRouteImport } from './routes/_app/room'
import { Route as AppShopRouteImport } from './routes/_app/shop'
import { Route as AppItemItemIdRouteImport } from './routes/_app/item.$itemId'
import { Route as AppUUserIdRouteImport } from './routes/_app/u.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppClosetRoute = AppClosetRouteImport.update({
  id: '/closet',
  path: '/closet',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppLooksRoute = AppLooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomRoute = AppRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppItemItemIdRoute = AppItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => AppRoute,
} as any)
const AppUUserIdRoute = AppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/add': typeof AppAddRoute
  '/closet': typeof AppClosetRoute
  '/explore': typeof AppExploreRoute
  '/feed': typeof AppFeedRoute
  '/looks': typeof AppLooksRoute
  '/me': typeof AppMeRoute
  '/room': typeof AppRoomRoute
  '/shop': typeof AppShopRoute
  '/item/$itemId': typeof AppItemItemIdRoute
  '/u/$userId': typeof AppUUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/add': typeof AppAddRoute
  '/closet': typeof AppClosetRoute
  '/explore': typeof AppExploreRoute
  '/feed': typeof AppFeedRoute
  '/looks': typeof AppLooksRoute
  '/me': typeof AppMeRoute
  '/room': typeof AppRoomRoute
  '/shop': typeof AppShopRoute
  '/item/$itemId': typeof AppItemItemIdRoute
  '/u/$userId': typeof AppUUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/add': typeof AppAddRoute
  '/_app/closet': typeof AppClosetRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/looks': typeof AppLooksRoute
  '/_app/me': typeof AppMeRoute
  '/_app/room': typeof AppRoomRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/item/$itemId': typeof AppItemItemIdRoute
  '/_app/u/$userId': typeof AppUUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/add'
    | '/closet'
    | '/explore'
    | '/feed'
    | '/looks'
    | '/me'
    | '/room'
    | '/shop'
    | '/item/$itemId'
    | '/u/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/add'
    | '/closet'
    | '/explore'
    | '/feed'
    | '/looks'
    | '/me'
    | '/room'
    | '/shop'
    | '/item/$itemId'
    | '/u/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/add'
    | '/_app/closet'
    | '/_app/explore'
    | '/_app/feed'
    | '/_app/looks'
    | '/_app/me'
    | '/_app/room'
    | '/_app/shop'
    | '/_app/item/$itemId'
    | '/_app/u/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/add': {
      id: '/_app/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/closet': {
      id: '/_app/closet'
      path: '/closet'
      fullPath: '/closet'
      preLoaderRoute: typeof AppClosetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/looks': {
      id: '/_app/looks'
      path: '/looks'
      fullPath: '/looks'
      preLoaderRoute: typeof AppLooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/room': {
      id: '/_app/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof AppRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/item/$itemId': {
      id: '/_app/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof AppItemItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/u/$userId': {
      id: '/_app/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AppUUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppClosetRoute: typeof AppClosetRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFeedRoute: typeof AppFeedRoute
  AppLooksRoute: typeof AppLooksRoute
  AppMeRoute: typeof AppMeRoute
  AppRoomRoute: typeof AppRoomRoute
  AppShopRoute: typeof AppShopRoute
  AppItemItemIdRoute: typeof AppItemItemIdRoute
  AppUUserIdRoute: typeof AppUUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppClosetRoute: AppClosetRoute,
  AppExploreRoute: AppExploreRoute,
  AppFeedRoute: AppFeedRoute,
  AppLooksRoute: AppLooksRoute,
  AppMeRoute: AppMeRoute,
  AppRoomRoute: AppRoomRoute,
  AppShopRoute: AppShopRoute,
  AppItemItemIdRoute: AppItemItemIdRoute,
  AppUUserIdRoute: AppUUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
